# Generated by Django 6.0.8 on 2026-08-13 16:38

import accounts.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_disable_historical_seed_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, validators=[accounts.validators.validate_e164_phone])),
                ('purpose', models.CharField(choices=[('SIGNUP', 'Signup'), ('PASSWORD_RESET', 'Password reset')], max_length=24)),
                ('code_digest', models.CharField(editable=False, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OTPCode',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['phone_number', 'purpose', '-created_at'], name='accounts_ot_phone_n_4b074c_idx'),
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(condition=models.Q(('consumed_at__isnull', True)), fields=['expires_at'], name='otp_unconsumed_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='otpchallenge',
            constraint=models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True)), fields=('phone_number', 'purpose'), name='one_unconsumed_otp_per_phone_purpose'),
        ),
        migrations.AddConstraint(
            model_name='otpchallenge',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gt', 0)), name='otp_max_attempts_positive'),
        ),
        migrations.AddConstraint(
            model_name='otpchallenge',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts'))), name='otp_attempts_within_limit'),
        ),
    ]
