# Generated by Django 6.0.8 on 2026-08-13 19:34

from django.db import migrations, models


def remove_invalid_legacy_ratings(apps, schema_editor):
    Doctor = apps.get_model("accounts", "Doctor")
    DoctorReview = apps.get_model("accounts", "DoctorReview")
    DoctorReview.objects.exclude(user__role="USER").delete()
    DoctorReview.objects.exclude(rating__gte=1, rating__lte=5).delete()
    likes_through = Doctor._meta.get_field("likes").remote_field.through
    likes_through.objects.exclude(user__role="USER").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_secure_doctor_document_assets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorreview',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AlterUniqueTogether(
            name='doctorreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddIndex(
            model_name='doctorreview',
            index=models.Index(fields=['doctor', '-created_at', '-id'], name='rating_doctor_created_idx'),
        ),
        migrations.RunPython(remove_invalid_legacy_ratings, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='doctorreview',
            constraint=models.UniqueConstraint(fields=('doctor', 'user'), name='unique_patient_rating_per_doctor'),
        ),
        migrations.AddConstraint(
            model_name='doctorreview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='doctor_rating_between_1_and_5'),
        ),
    ]
