# Generated by Django 6.0.8 on 2026-08-13 18:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_appointment_claim_otp'),
        ('core', '0001_initial'),
        ('messaging', '0002_message_messaging_m_thread__a5aa52_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('CHAT_ATTACHMENT', 'Chat attachment'), ('VERIFICATION_DOCUMENT', 'Verification document'), ('PROFILE_PICTURE', 'Profile picture')], max_length=32)),
                ('original_name', models.CharField(max_length=255)),
                ('expected_size', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1073741824)])),
                ('actual_size', models.BigIntegerField(blank=True, null=True)),
                ('claimed_mime', models.CharField(max_length=127)),
                ('detected_mime', models.CharField(blank=True, default='', max_length=127)),
                ('sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')])),
                ('verified_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('QUARANTINED', 'Quarantined'), ('AVAILABLE', 'Available'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], default='PENDING', max_length=16)),
                ('scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_assets', to=settings.AUTH_USER_MODEL)),
                ('scope_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_file_assets', to='accounts.doctor')),
                ('scope_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_file_assets', to='messaging.messagethread')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_upload_id', models.CharField(blank=True, default='', max_length=512)),
                ('part_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5242880), django.core.validators.MaxValueValidator(67108864)])),
                ('expected_part_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('state', models.CharField(choices=[('CREATED', 'Created'), ('UPLOADING', 'Uploading'), ('COMPLETING', 'Completing'), ('COMPLETED', 'Completed'), ('ABORTED', 'Aborted'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='CREATED', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_session', to='core.fileasset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['owner', 'state', '-created_at'], name='asset_owner_state_created_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['purpose', 'state', '-created_at'], name='asset_purpose_state_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(condition=models.Q(('state__in', ('PENDING', 'UPLOADING'))), fields=['expires_at'], name='asset_incomplete_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['PENDING', 'UPLOADING', 'QUARANTINED', 'AVAILABLE', 'FAILED', 'DELETED'])), name='asset_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(('scan_status__in', ['PENDING', 'CLEAN', 'INFECTED', 'FAILED'])), name='asset_scan_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(('expected_size__gte', 1), ('expected_size__lte', 1073741824)), name='asset_expected_size_valid'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(('actual_size__isnull', True), ('actual_size__gte', 1), _connector='OR'), name='asset_actual_size_valid'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purpose', 'CHAT_ATTACHMENT'), ('scope_doctor__isnull', True), ('scope_thread__isnull', False)), models.Q(('purpose', 'VERIFICATION_DOCUMENT'), ('scope_doctor__isnull', False), ('scope_thread__isnull', True)), models.Q(('purpose', 'PROFILE_PICTURE'), ('scope_doctor__isnull', True), ('scope_thread__isnull', True)), _connector='OR'), name='asset_purpose_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'AVAILABLE'), _negated=True), models.Q(('scan_status', 'CLEAN'), ('actual_size', models.F('expected_size')), ('verified_sha256', models.F('sha256'))), _connector='OR'), name='available_asset_is_verified'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['owner', 'state', '-created_at'], name='upload_owner_state_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(condition=models.Q(('state__in', ('CREATED', 'UPLOADING', 'COMPLETING'))), fields=['expires_at'], name='upload_active_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['CREATED', 'UPLOADING', 'COMPLETING', 'COMPLETED', 'ABORTED', 'EXPIRED', 'FAILED'])), name='upload_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('part_size__gte', 5242880)), name='upload_part_size_min'),
        ),
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('expected_part_count__gte', 1), ('expected_part_count__lte', 10000)), name='upload_part_count_valid'),
        ),
    ]
