# Generated by Django 6.0.8 on 2026-08-13 21:05

import django.db.models.deletion
from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('accounts', '0013_remove_doctor_accounts_do_verific_a9ada0_idx_and_more'),
        ('appointments', '0004_guest_booking_identity'),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='appointment',
            name='appointment_status_8fe9d7_idx',
        ),
        RemoveIndexConcurrently(
            model_name='appointmentslot',
            name='appointment_date_475da9_idx',
        ),
        RemoveIndexConcurrently(
            model_name='appointmentslot',
            name='appointment_start_a_2d6933_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'DROP INDEX CONCURRENTLY IF EXISTS appointments_appointment_patient_id_631d13da',
                    reverse_sql=(
                        'CREATE INDEX CONCURRENTLY IF NOT EXISTS '
                        'appointments_appointment_patient_id_631d13da '
                        'ON appointments_appointment (patient_id)'
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='appointment',
                    name='patient',
                    field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.normaluser'),
                ),
            ],
        ),
        AddIndexConcurrently(
            model_name='appointmentslot',
            index=models.Index(fields=['date', 'start_at'], name='slot_date_start_idx'),
        ),
    ]
