# Generated by Django 6.0.8 on 2026-08-22 01:34

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_seed_initial_public_data'),
        ('appointments', '0008_normalize_initial_visit_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('weekday', 'start_time', 'starts_on', 'pk'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='appointmentslot',
            name='unique_slot_start_capacity',
        ),
        migrations.RemoveConstraint(
            model_name='appointmentslot',
            name='exclude_overlapping_slots_capacity',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='availability_slots', to='accounts.doctor'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['doctor', 'date', 'start_at'], name='slot_doctor_date_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.UniqueConstraint(condition=models.Q(('doctor__isnull', True)), fields=('start_at', 'capacity_index'), name='unique_global_slot_start_capacity'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.UniqueConstraint(condition=models.Q(('doctor__isnull', False)), fields=('doctor', 'start_at', 'capacity_index'), name='unique_doctor_slot_start_capacity'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('doctor__isnull', True), ('status__in', ['AVAILABLE', 'BOOKED'])), expressions=[(models.Func(models.F('start_at'), models.F('end_at'), function='TSTZRANGE', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&'), ('capacity_index', '=')], name='exclude_global_slot_overlap'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('doctor__isnull', False), ('status__in', ['AVAILABLE', 'BOOKED'])), expressions=[(models.Func(models.F('start_at'), models.F('end_at'), function='TSTZRANGE', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&'), ('capacity_index', '='), ('doctor', '=')], name='exclude_doctor_slot_overlap'),
        ),
        migrations.AddField(
            model_name='doctoravailabilityrule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='accounts.doctor'),
        ),
        migrations.AddIndex(
            model_name='doctoravailabilityrule',
            index=models.Index(fields=['doctor', 'weekday', 'is_active', 'starts_on', 'ends_on'], name='doctor_rule_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctoravailabilityrule',
            constraint=models.UniqueConstraint(fields=('doctor', 'weekday', 'start_time', 'end_time', 'slot_duration_minutes', 'starts_on', 'ends_on'), name='unique_doctor_availability_rule'),
        ),
        migrations.AddConstraint(
            model_name='doctoravailabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='doctor_rule_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='doctoravailabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__lte', models.F('ends_on'))), name='doctor_rule_date_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='doctoravailabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='doctor_rule_weekday_valid'),
        ),
        migrations.AddConstraint(
            model_name='doctoravailabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('slot_duration_minutes__gte', 5), ('slot_duration_minutes__lte', 480)), name='doctor_rule_duration_valid'),
        ),
    ]
