# Generated by Django 6.0.8 on 2026-08-13 21:05

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('accounts', '0012_alter_doctorreview_options_and_more'),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='doctor',
            name='accounts_do_verific_a9ada0_idx',
        ),
        RemoveIndexConcurrently(
            model_name='user',
            name='accounts_us_usernam_c0ea66_idx',
        ),
    ]
