# Generated by Django 6.0.8 on 2026-08-13 17:06

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.contrib.postgres.operations import BtreeGistExtension
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_integrity'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='AvailabilityBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('CLOSED', 'Closed'), ('CUSTOM', 'Custom hours')], max_length=12)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='Asia/Tehran', editable=False, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('capacity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='capacity_index',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='generated_by_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='start_at',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['start_at'], name='appointment_start_a_2d6933_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.UniqueConstraint(fields=('start_at', 'capacity_index'), name='unique_slot_start_capacity'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['AVAILABLE', 'BOOKED'])), expressions=[(models.Func(models.F('start_at'), models.F('end_at'), function='TSTZRANGE', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&'), ('capacity_index', '=')], name='exclude_overlapping_slots_capacity'),
        ),
        migrations.AddField(
            model_name='availabilityoverride',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='appointments.clinicschedule'),
        ),
        migrations.AddField(
            model_name='weeklyavailabilityrule',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rules', to='appointments.clinicschedule'),
        ),
        migrations.AddField(
            model_name='availabilitybreak',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='appointments.weeklyavailabilityrule'),
        ),
        migrations.AddConstraint(
            model_name='availabilityoverride',
            constraint=models.UniqueConstraint(fields=('schedule', 'date'), name='one_availability_override_per_date'),
        ),
        migrations.AddConstraint(
            model_name='availabilityoverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('capacity__isnull', True), ('end_time__isnull', True), ('kind', 'CLOSED'), ('slot_duration_minutes__isnull', True), ('start_time__isnull', True)), models.Q(('capacity__gte', 1), ('capacity__lte', 20), ('end_time__isnull', False), ('kind', 'CUSTOM'), ('slot_duration_minutes__gte', 5), ('slot_duration_minutes__lte', 480), ('start_time__isnull', False), ('start_time__lt', models.F('end_time'))), _connector='OR'), name='availability_override_fields_match_kind'),
        ),
        migrations.AddIndex(
            model_name='weeklyavailabilityrule',
            index=models.Index(fields=['schedule', 'weekday', 'is_active'], name='appointment_schedul_e5b208_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklyavailabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='weekly_rule_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='weeklyavailabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='weekly_rule_valid_weekday'),
        ),
        migrations.AddConstraint(
            model_name='weeklyavailabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('slot_duration_minutes__gte', 5), ('slot_duration_minutes__lte', 480)), name='weekly_rule_valid_duration'),
        ),
        migrations.AddConstraint(
            model_name='weeklyavailabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1), ('capacity__lte', 20)), name='weekly_rule_valid_capacity'),
        ),
        migrations.AddConstraint(
            model_name='availabilitybreak',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='availability_break_start_before_end'),
        ),
    ]
