# Generated by Django 6.0.6 on 2026-06-18 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'read_by_recipient'], name='messaging_m_thread__a5aa52_idx'),
        ),
    ]
