# Generated by Django 6.0.8 on 2026-08-13 18:13

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_attachments(apps, schema_editor):
    MessageAttachment = apps.get_model("messaging", "MessageAttachment")
    FileAsset = apps.get_model("core", "FileAsset")
    for attachment in MessageAttachment.objects.select_related("message").iterator(chunk_size=500):
        storage_key = attachment.file_key or f"legacy/chat/{attachment.pk}"
        if FileAsset.objects.filter(storage_key=storage_key).exists():
            storage_key = f"legacy/chat/duplicate/{attachment.pk}"
        asset = FileAsset.objects.create(
            owner_id=attachment.message.sender_id,
            purpose="CHAT_ATTACHMENT",
            scope_thread_id=attachment.message.thread_id,
            original_name=attachment.file_name or f"attachment-{attachment.pk}",
            expected_size=max(1, min(attachment.file_size or 0, 1024 * 1024 * 1024)),
            claimed_mime=attachment.file_content_type or "application/octet-stream",
            sha256="0" * 64,
            storage_key=storage_key,
            state="QUARANTINED",
            scan_status="PENDING",
        )
        attachment.asset_id = asset.pk
        attachment.save(update_fields=("asset",))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fileasset_uploadsession_and_more'),
        ('messaging', '0002_message_messaging_m_thread__a5aa52_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='asset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_attachment', to='core.fileasset'),
        ),
        migrations.RunPython(migrate_legacy_attachments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='messageattachment',
            name='file_content_type',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='file_key',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='file_url',
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='message_attachment', to='core.fileasset'),
        ),
    ]
