# Generated by Django 6.0.8 on 2026-08-13 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_message_snapshots_and_read_states(apps, schema_editor):
    Message = apps.get_model('messaging', 'Message')
    MessageThread = apps.get_model('messaging', 'MessageThread')
    ThreadReadState = apps.get_model('messaging', 'ThreadReadState')

    for message in Message.objects.select_related('sender').iterator(chunk_size=1000):
        if message.sender_id:
            Message.objects.filter(pk=message.pk).update(
                sender_first_name=message.sender.first_name,
                sender_last_name=message.sender.last_name,
            )

    for thread in MessageThread.objects.iterator(chunk_size=500):
        readers = [thread.participant_id, thread.assigned_admin_id]
        for reader_id in {reader_id for reader_id in readers if reader_id}:
            latest = (
                Message.objects.filter(
                    thread_id=thread.pk,
                    read_by_recipient=True,
                )
                .exclude(sender_id=reader_id)
                .order_by('-created_at', '-id')
                .first()
            )
            if latest:
                ThreadReadState.objects.update_or_create(
                    thread_id=thread.pk,
                    user_id=reader_id,
                    defaults={'last_read_at': latest.read_at or latest.created_at},
                )


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_remove_messageattachment_file_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadReadState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at', 'id')},
        ),
        migrations.AlterModelOptions(
            name='messagethread',
            options={'ordering': ('-last_message_at', '-created_at', '-id')},
        ),
        migrations.RemoveConstraint(
            model_name='messagethread',
            name='unique_open_thread_per_participant_type',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_thread__1731c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_thread__a5aa52_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagethread',
            name='messaging_m_thread__ee954a_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagethread',
            name='messaging_m_partici_504b9c_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='message',
            name='visibility',
            field=models.CharField(choices=[('PARTICIPANTS', 'Participants'), ('ADMINS_ONLY', 'Administrators only')], default='PARTICIPANTS', max_length=16),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_message_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='guest_first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='guest_last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('USER', 'User'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin'), ('GUEST', 'Guest')], max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='messaging.messagethread'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='messaging.message'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', '-created_at', '-id'], name='messaging_m_thread__f3c5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'visibility', 'is_deleted', '-created_at'], name='messaging_m_thread__93fe4a_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['thread_type', 'status', '-last_message_at'], name='messaging_m_thread__7e0d44_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['participant', '-last_message_at'], name='messaging_m_partici_020e11_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['guest_phone', 'status'], name='messaging_m_guest_p_909a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['deleted_at'], name='messaging_m_deleted_00e4ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('body__length__lte', 4000)), name='message_body_max_4000'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ('PARTICIPANTS', 'ADMINS_ONLY'))), name='message_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sender__isnull', True), ('sender_type', 'GUEST')), models.Q(models.Q(('sender_type', 'GUEST'), _negated=True), ('sender__isnull', False)), _connector='OR'), name='message_sender_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'OPEN')), fields=('participant', 'thread_type'), name='unique_open_thread_per_participant_type'),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('participant__isnull', True), ('status', 'OPEN')), fields=('guest_phone', 'thread_type'), name='unique_open_guest_thread_per_phone_type'),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_phone', ''), ('participant__isnull', False)), models.Q(('participant__isnull', True), models.Q(('guest_phone', ''), _negated=True)), _connector='OR'), name='thread_has_one_participant_identity'),
        ),
        migrations.AddField(
            model_name='threadreadstate',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='messaging.messagethread'),
        ),
        migrations.AddField(
            model_name='threadreadstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            migrate_message_snapshots_and_read_states,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_by_recipient',
        ),
        migrations.AddIndex(
            model_name='threadreadstate',
            index=models.Index(fields=['user', 'thread', 'last_read_at'], name='messaging_t_user_id_a836a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='threadreadstate',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='unique_thread_read_state_per_user'),
        ),
    ]
