# Generated by Django 6.0.8 on 2026-08-13 21:05

import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('messaging', '0004_threadreadstate_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='message',
            name='messaging_m_thread__93fe4a_idx',
        ),
        RemoveIndexConcurrently(
            model_name='messageattachment',
            name='messaging_m_is_3d_s_2a376c_idx',
        ),
        RemoveIndexConcurrently(
            model_name='messagethread',
            name='messaging_m_thread__7e0d44_idx',
        ),
        RemoveIndexConcurrently(
            model_name='messagethread',
            name='messaging_m_partici_020e11_idx',
        ),
        RemoveIndexConcurrently(
            model_name='messagethread',
            name='messaging_m_guest_p_909a7f_idx',
        ),
        RemoveIndexConcurrently(
            model_name='messagethread',
            name='messaging_m_deleted_00e4ef_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'DROP INDEX CONCURRENTLY IF EXISTS messaging_message_thread_id_f689027f',
                    reverse_sql=(
                        'CREATE INDEX CONCURRENTLY IF NOT EXISTS '
                        'messaging_message_thread_id_f689027f '
                        'ON messaging_message (thread_id)'
                    ),
                ),
                migrations.RunSQL(
                    'DROP INDEX CONCURRENTLY IF EXISTS messaging_messageattachment_is_3d_scan_f9988946',
                    reverse_sql=(
                        'CREATE INDEX CONCURRENTLY IF NOT EXISTS '
                        'messaging_messageattachment_is_3d_scan_f9988946 '
                        'ON messaging_messageattachment (is_3d_scan)'
                    ),
                ),
                migrations.RunSQL(
                    'DROP INDEX CONCURRENTLY IF EXISTS messaging_messagethread_participant_id_5e3ac72a',
                    reverse_sql=(
                        'CREATE INDEX CONCURRENTLY IF NOT EXISTS '
                        'messaging_messagethread_participant_id_5e3ac72a '
                        'ON messaging_messagethread (participant_id)'
                    ),
                ),
                migrations.RunSQL(
                    'DROP INDEX CONCURRENTLY IF EXISTS messaging_messagethread_thread_type_90141cda',
                    reverse_sql=(
                        'CREATE INDEX CONCURRENTLY IF NOT EXISTS '
                        'messaging_messagethread_thread_type_90141cda '
                        'ON messaging_messagethread (thread_type)'
                    ),
                ),
                migrations.RunSQL(
                    'DROP INDEX CONCURRENTLY IF EXISTS messaging_messagethread_thread_type_90141cda_like',
                    reverse_sql=(
                        'CREATE INDEX CONCURRENTLY IF NOT EXISTS '
                        'messaging_messagethread_thread_type_90141cda_like '
                        'ON messaging_messagethread (thread_type varchar_pattern_ops)'
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='message',
                    name='thread',
                    field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='messaging.messagethread'),
                ),
                migrations.AlterField(
                    model_name='messageattachment',
                    name='is_3d_scan',
                    field=models.BooleanField(default=False),
                ),
                migrations.AlterField(
                    model_name='messagethread',
                    name='participant',
                    field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_threads', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name='messagethread',
                    name='thread_type',
                    field=models.CharField(choices=[('USER_ADMIN', 'User-Admin'), ('DOCTOR_ADMIN', 'Doctor-Admin')], max_length=20),
                ),
            ],
        ),
        AddIndexConcurrently(
            model_name='message',
            index=models.Index(fields=['thread', 'visibility', 'is_deleted', '-created_at', '-id'], name='messaging_m_thread__9b87ef_idx'),
        ),
        AddIndexConcurrently(
            model_name='messagethread',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['-last_message_at', '-created_at', '-id'], name='thread_active_order_idx'),
        ),
        AddIndexConcurrently(
            model_name='messagethread',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['participant', '-last_message_at', '-created_at', '-id'], name='thread_participant_order_idx'),
        ),
    ]
