# Generated by Django 6.0.8 on 2026-08-22 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_seed_initial_public_data'),
        ('messaging', '0005_remove_message_messaging_m_thread__93fe4a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedChatContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='messagethread',
            name='thread_has_one_participant_identity',
        ),
        migrations.AddField(
            model_name='messagethread',
            name='direct_participant_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_message_threads_as_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='direct_participant_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_message_threads_as_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='thread_type',
            field=models.CharField(choices=[('USER_ADMIN', 'User-Admin'), ('DOCTOR_ADMIN', 'Doctor-Admin'), ('DIRECT', 'Direct conversation')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('thread_type', 'DIRECT')), fields=['direct_participant_one', '-last_message_at', '-created_at'], name='thread_direct_one_order_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('thread_type', 'DIRECT')), fields=['direct_participant_two', '-last_message_at', '-created_at'], name='thread_direct_two_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'OPEN'), ('thread_type', 'DIRECT')), fields=('direct_participant_one', 'direct_participant_two'), name='unique_open_direct_thread_pair'),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direct_participant_one__isnull', False), ('direct_participant_one__lt', models.F('direct_participant_two')), ('direct_participant_two__isnull', False), ('guest_phone', ''), ('participant__isnull', True), ('thread_type', 'DIRECT')), models.Q(models.Q(('thread_type', 'DIRECT'), _negated=True), ('direct_participant_one__isnull', True), ('direct_participant_two__isnull', True), models.Q(models.Q(('guest_phone', ''), ('participant__isnull', False)), models.Q(('participant__isnull', True), models.Q(('guest_phone', ''), _negated=True)), _connector='OR')), _connector='OR'), name='thread_participant_shape_valid'),
        ),
        migrations.AddField(
            model_name='pinnedchatcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pinnedchatcontact',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_chat_contacts', to='accounts.doctor'),
        ),
        migrations.AddIndex(
            model_name='pinnedchatcontact',
            index=models.Index(fields=['owner', 'created_at', 'id'], name='messaging_p_owner_i_a058e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='pinnedchatcontact',
            constraint=models.UniqueConstraint(fields=('owner', 'contact'), name='unique_pinned_chat_contact'),
        ),
        migrations.AddConstraint(
            model_name='pinnedchatcontact',
            constraint=models.CheckConstraint(condition=models.Q(('owner', models.F('contact')), _negated=True), name='pinned_chat_contact_not_self'),
        ),
    ]
