# Generated by Django 6.0.8 on 2026-08-13 18:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fileasset_uploadsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('part_number', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('etag', models.CharField(max_length=255)),
                ('checksum_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')])),
                ('recorded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('part_number',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='uploadsession',
            name='upload_state_valid',
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='client_upload_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPLOADING', 'Uploading'), ('COMPLETING', 'Completing'), ('COMPLETED', 'Completed'), ('ABORTED', 'Aborted'), ('ABORTING', 'Aborting'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='CREATED', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.UniqueConstraint(fields=('owner', 'client_upload_id'), name='unique_owner_client_upload'),
        ),
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('CREATED', 'UPLOADING', 'COMPLETING', 'COMPLETED', 'ABORTED', 'ABORTING', 'EXPIRED', 'FAILED'))), name='upload_state_valid'),
        ),
        migrations.AddField(
            model_name='uploadpart',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_parts', to='core.uploadsession'),
        ),
        migrations.AddConstraint(
            model_name='uploadpart',
            constraint=models.UniqueConstraint(fields=('session', 'part_number'), name='unique_upload_session_part'),
        ),
        migrations.AddConstraint(
            model_name='uploadpart',
            constraint=models.CheckConstraint(condition=models.Q(('part_number__gte', 1), ('part_number__lte', 10000)), name='upload_part_number_valid'),
        ),
        migrations.AddConstraint(
            model_name='uploadpart',
            constraint=models.CheckConstraint(condition=models.Q(('size__gte', 1)), name='upload_part_size_valid'),
        ),
    ]
