# Generated by Django 6.0.8 on 2026-08-13 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_secure_doctor_document_assets'),
        ('core', '0003_uploadpart_remove_uploadsession_upload_state_valid_and_more'),
        ('messaging', '0003_remove_messageattachment_file_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccessAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('DOWNLOAD_GRANTED', 'Download granted'), ('SCAN_CLEAN', 'Scan clean'), ('SCAN_REJECTED', 'Scan rejected'), ('RETENTION_DELETE', 'Retention delete')], max_length=24)),
                ('outcome', models.CharField(default='SUCCESS', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='fileasset',
            name='asset_scan_status_valid',
        ),
        migrations.AddField(
            model_name='fileasset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='retention_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='scan_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCANNING', 'Scanning'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(condition=models.Q(('state__in', ('AVAILABLE', 'FAILED', 'DELETED'))), fields=['retention_until'], name='asset_retention_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(('scan_status__in', ('PENDING', 'SCANNING', 'CLEAN', 'INFECTED', 'FAILED'))), name='asset_scan_status_valid'),
        ),
        migrations.AddField(
            model_name='fileaccessaudit',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_access_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileaccessaudit',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_audits', to='core.fileasset'),
        ),
        migrations.AddIndex(
            model_name='fileaccessaudit',
            index=models.Index(fields=['asset', '-created_at'], name='file_audit_asset_created_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccessaudit',
            index=models.Index(fields=['actor', '-created_at'], name='file_audit_actor_created_idx'),
        ),
    ]
